package lab

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/doc"
	"go/format"
	"go/parser"
	"go/token"
	"maps"
	"os"
	"slices"
	"strings"
	"testing"

	"github.com/shpaker/kinescope"
)

var update = flag.Bool("update", false, "write docs_gen.go afresh")

// The library's root, from this package
const libraryDir = "../../../.."

// TestDocs checks docs_gen.go holds the library's docs as they are now; with
// -update (go generate) it writes them.
func TestDocs(t *testing.T) {
	want, err := generateDocs()
	if err != nil {
		t.Fatal(err)
	}
	if *update {
		if err := os.WriteFile("docs_gen.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile("docs_gen.go")
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Error("docs_gen.go is stale: run go generate ./cmd/kinescope-lab/...")
	}
}

// generateDocs is docs_gen.go: the docs of the effects, the kinds of
// sources and the episodes, and of the effects' fields.
func generateDocs() ([]byte, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, libraryDir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var files []*ast.File
	for _, f := range pkgs["kinescope"].Files {
		files = append(files, f)
	}
	pkg, err := doc.NewFromFiles(fset, files, "github.com/shpaker/kinescope")
	if err != nil {
		return nil, err
	}

	var names []string
	for _, e := range kinescope.Effects() {
		names = append(names, camel(e.Name()))
	}
	for _, k := range kinds {
		names = append(names, k.typ)
	}
	for _, e := range episodes {
		names = append(names, e.constructor)
	}

	types := make(map[string]string)
	fields := make(map[kinescope.ParamKey]string)
	for _, typ := range pkg.Types {
		if slices.Contains(names, typ.Name) {
			types[typ.Name] = paragraph(typ.Doc)
		}
		for _, f := range typ.Funcs {
			if slices.Contains(names, f.Name) {
				types[f.Name] = paragraph(f.Doc)
			}
		}
	}
	for _, e := range kinescope.Effects() {
		typ := camel(e.Name())
		i := slices.IndexFunc(pkg.Types, func(t *doc.Type) bool { return t.Name == typ })
		if i < 0 {
			return nil, fmt.Errorf("no type %s", typ)
		}
		spec := pkg.Types[i].Decl.Specs[0].(*ast.TypeSpec)
		st, ok := spec.Type.(*ast.StructType)
		if !ok {
			return nil, fmt.Errorf("%s is not a struct", typ)
		}
		for _, p := range e.Params() {
			_, field, _ := strings.Cut(string(p.Key), ".")
			for _, f := range st.Fields.List {
				if len(f.Names) == 0 || f.Names[0].Name != camel(field) {
					continue
				}
				if text := paragraph(f.Comment.Text() + f.Doc.Text()); text != "" {
					fields[p.Key] = text
				}
			}
		}
	}

	var b bytes.Buffer
	b.WriteString("// Code generated by go test -update; DO NOT EDIT.\n\npackage lab\n\n")
	b.WriteString("import \"github.com/shpaker/kinescope\"\n\n")
	b.WriteString("// typeDocs are the docs of the library's effects, kinds of sources and\n")
	b.WriteString("// episodes, by their names in Go.\nvar typeDocs = map[string]string{\n")
	for _, name := range slices.Sorted(maps.Keys(types)) {
		fmt.Fprintf(&b, "%q: %q,\n", name, types[name])
	}
	b.WriteString("}\n\n// fieldDocs are the docs of the effects' fields, by their params' keys.\n")
	b.WriteString("var fieldDocs = map[kinescope.ParamKey]string{\n")
	for _, key := range slices.Sorted(maps.Keys(fields)) {
		fmt.Fprintf(&b, "%q: %q,\n", key, fields[key])
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

// paragraph is the first paragraph of a doc, on one line.
func paragraph(text string) string {
	first, _, _ := strings.Cut(strings.TrimSpace(text), "\n\n")
	return strings.Join(strings.Fields(first), " ")
}
