// Code generated by go test -update; DO NOT EDIT.

package lab

import "github.com/shpaker/kinescope"

// typeDocs are the docs of the library's effects, kinds of sources and
// episodes, by their names in Go.
var typeDocs = map[string]string{
	"Afterglow":    "Afterglow keeps the phosphor glowing after the beam has passed: bright moving things leave a short trail, the blue one longest.",
	"ApertureMask": "ApertureMask is the phosphor's red, green and blue stripes, one triad per three screen pixels.",
	"Convergence":  "Convergence puts the red and blue guns out of register: their beams part towards the edges of the screen, and on a worn set drift apart sideways all over it.",
	"Corners":      "Corners round the picture's corners to the tube's outline.",
	"Curvature":    "Curvature bulges the glass: the picture bows out towards the tube's corners.",
	"Degauss":      "Degauss is the degaussing coil shaking the mask: the picture wobbles and settles. Its strength rests at zero and is driven by the Degauss episode.",
	"Degaussing":   "Degaussing is the coil shaking the mask: the picture wobbles and settles.",
	"Drift":        "Drift wanders smoothly and at random between 0 and 1, like the reception of a far station: now clearer, now worse.",
	"Flicker":      "Flicker trembles the whole picture's brightness.",
	"Glass":        "Glass is the tube's glass catching the room's light: black is never quite black, and a soft reflection sits in the upper left corner.",
	"Glow":         "Glow bleeds the light of bright areas around them.",
	"Grain":        "Grain is the signal's snow: fine noise, new every frame, seen on black too.",
	"Hum":          "Hum is the mains hum: a bar rolling slowly down the picture, light or dark.",
	"Interlace":    "Interlace draws the lines in two fields taking turns, frame by frame: the lines of the field not drawn fade, and the picture shimmers.",
	"Jitter":       "Jitter tears the lines for a moment, as when the horizontal sync slips.",
	"Power":        "Power squeezes the raster as the tube warms up or dies — a dot, a line, the picture — and flashes the beam. The TV drives it on PowerOn and PowerOff; at rest it is the whole picture.",
	"Ripple":       "Ripple is the signal shivering as a channel is switched: the lines tear a little, the grain thickens and snow flickers, all dying out.",
	"Roll":         "Roll slips the picture down as the vertical sync is lost: Strength is the share of the height it has slipped, the blanking bar crossing with it. It rests at zero and is driven by the Roll episode.",
	"RollOver":     "RollOver slips the picture a whole height down, as when the vertical sync is lost, the blanking bar crossing with it.",
	"Scanlines":    "Scanlines are the beam's lines, one per frame row: dark gaps between them, narrower where the beam is bright and wide.",
	"Signal":       "Signal is a level the game sets, frame by frame: a fact of the game, such as the set being shaken. Get its Level with TV.Signal.",
	"SlotMask":     "SlotMask is the phosphor of a shadow-mask set: red, green and blue stripes cut by slots, each column of triads half a slot below the last.",
	"Snow":         "Snow is the screen drowning in snow, as when the signal is lost. Its strength rests at zero and is driven by the Snow episode.",
	"SnowBurst":    "SnowBurst drowns the picture in snow for a moment.",
	"Softness":     "Softness spreads the beam between neighboring pixels of a line: 0 keeps them square, 1 blends them smoothly. It shows on a screen scaled by a fraction, where square pixels come out uneven.",
	"Tear":         "Tear shifts the lines sideways, as when the set is knocked or the horizontal sync slips: in a running wave, and in bands of lines torn at random. Its strength usually rests at zero and is driven: by a signal such as a shake, or by a glitch.",
	"Vignette":     "Vignette dims the picture towards its corners.",
	"Wave":         "Wave rises from 0 to 1 and falls back, again and again.",
}

// fieldDocs are the docs of the effects' fields, by their params' keys.
var fieldDocs = map[kinescope.ParamKey]string{
	"afterglow.decay":         "the share of the glow kept from one frame to the next",
	"aperture_mask.min_scale": "MinScale is the screen pixels per frame pixel the mask needs: below it the mask fades out.",
	"aperture_mask.strength":  "how much the stripes show",
	"convergence.amount":      "the parting at the edges, outwards, in frame pixels",
	"convergence.offset":      "Offset is the sideways drift, red to the right and blue to the left: half of it in the middle, all of it at the edges, in frame pixels.",
	"corners.radius":          "in frame pixels",
	"curvature.x":             "bulge across, the stronger the nearer the top and bottom",
	"curvature.y":             "bulge down, the stronger the nearer the sides",
	"flicker.frequency":       "trembles per second",
	"flicker.strength":        "the share of brightness the picture trembles by",
	"glass.level":             "the glass's own light on black",
	"glow.radius":             "how far it spreads, in frame pixels",
	"glow.strength":           "how much of the glow is added",
	"glow.threshold":          "the brightness the glow starts at",
	"hum.period":              "seconds the bar takes to cross the picture",
	"hum.strength":            "how much brighter the bar is; below zero, darker",
	"hum.width":               "the bar's width, in the picture's heights",
	"interlace.min_scale":     "MinScale is the screen pixels per frame pixel the fields need: below it they fade out.",
	"power.flash":             "the beam's flash added to the picture",
	"power.height":            "the raster's height, 1 whole",
	"power.width":             "the raster's width, 1 whole",
	"scanlines.depth":         "how dark the gaps get",
	"scanlines.min_scale":     "MinScale is the screen pixels per frame pixel the lines need: below it they fade out, as too few pixels turn them into moiré.",
	"slot_mask.min_scale":     "MinScale is the screen pixels per frame pixel the mask needs: below it the mask fades out.",
	"tear.amplitude":          "the wave's shift of a line at full strength, in frame pixels",
	"tear.bands":              "Bands is the shift of the bands torn at random, in frame pixels. They last a moment, so Map leaves them out.",
	"tear.strength":           "0 calm, 1 fully torn",
}
